const productosData = {
    productos: [
        {
            nombre: "Arnés Strap-on Doble",
            precio: 45,
            imagen: "imagen/arnes.jpg",
            categorias: ["ropa", "accesorios", "arnés"],
            disponible: true,
            material: "Silicona",
            dimensiones: "17.5 cm y 12.5 cm",
            diámetro: "2.2 cm y 3.5 cm",
            incluye: "Dildos intercambiables",
            color: "Morado",
            fechaAgregado: "2026-03-12",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador Succionador de Clitorís y Estimulador de Punto G",
            precio: 45,
            imagen: "imagen/vibrador.jpg",
            categorias: ["vibradores"],
            disponible: true,
            material: "Silicona ABS",
            largo: "11 cm",
            diámetro: "3.4 cm",
            batería: "Carga USB Magnética",
            vibración: "9 modos",
            succion: "9 modos",
            color: "Rosado, Morado",
            control: "Por App",
            fechaAgregado: "2026-03-12",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Estimulador Prostático Masculino",
            precio: 65,
            imagen: "imagen/estimuladorhomb.jpg",
            categorias: ["vibradores", "hombre"],
            disponible: true,
            largo: "9.3 cm",
            diámetro: "2 cm",
            material: "Silicona ABS",
            batería: "1 Pila AAA (No incluida)",
            color: "Morado",
            vibración: "10 Formas de Vibración",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador Vaginal y Punto G (Control por APP)",
            precio: 30,
            imagen: "imagen/vibraVPG.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "8 cm",
            diámetro: "3.2 cm",
            material: "Silicona ABS",
            batería: "Carga USB",
            color: "Rosado, Morado",
            vibración: "9 Modos",
            control: "Por App",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador Doble Strap-on Sin Correa",
            precio: 65,
            imagen: "imagen/vibraDS.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "23 cm y 12 cm",
            diámetro: "4 cm",
            material: "Silicona ABS",
            batería: "Carga USB",
            color: "Morado",
            vibración: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },        
        {
            nombre: "Arnés Strap-on de Doble Vibrador",
            precio: 50,
            imagen: "imagen/arnes2.jpg",
            categorias: ["vibradores", "ropa", "accesorios"],
            disponible: true,
            largo: "18.5 cm y 13 cm",
            diámetro: "3.5 cm y 2.5 cm'",
            material: "Silicona ABS",
            batería: "3 Pilas AAA (No incluidas)",
            color: "Negro, Morado",
            vibración: "Ascendente",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },        
        {
            nombre: "Dildo Realista Con Ventosa (Mando Alámbrico)",
            precio: 35,
            imagen: "imagen/dildo.jpg",
            categorias: ["vibradores", "dildos"],
            disponible: true,
            largo: "18 cm",
            diámetro: "3.5 cm'",
            material: "Silicona ABS",
            batería: "2 Pilas AAA (No incluidas)",
            color: "Piel",
            vibración: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Sexy de Hombre",
            precio: 13,
            imagen: "imagen/lenceH.jpg",
            categorias: ["ropa", "lencería", "lencería hombre", "hombre"],
            disponible: true,
            talla: "Talla Única",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Dildo Realista Telescópico 3 en 1 (Mando inalámbrico)",
            precio: 45,
            imagen: "imagen/dildo2.jpg",
            categorias: ["vibradores", "dildos"],
            disponible: true,
            largo: "19 cm",
            diámetro: "3.5 cm'",
            material: "Silicona ABS",
            batería: "Carga USB Magnética",
            color: "Piel",
            vibración: "10 Modos",
            empuje: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Arnés Strap-on con Dildo de Ventosa",
            precio: 45,
            imagen: "imagen/arnes3.jpg",
            categorias: ["ropa", "accesorios"],
            disponible: true,
            largo: "21.5 cm",
            diámetro: "3.8 cm",
            material: "Silicona",
            color: "Marrón Claro, Morado",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador de Braga Magnético (Control por APP)",
            precio: 35,
            imagen: "imagen/vibraBrag.jpg",
            categorias: ["vibradores", "accesorios", "bragas"],
            disponible: true,
            largo: "9 cm",
            material: "Silicona ABS",
            batería: "Carga USB Magnética",
            color: "Verde",
            vibración: "9 Modos",
            control: "Por App",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Dildo de Ventosa Realista",
            precio: 30,
            imagen: "imagen/dildo4.jpg",
            categorias: ["dildos"],
            disponible: true,
            largo: "18 cm",
            diámetro: "3.5 cm",
            material: "Silicona Médica",
            color: "Piel",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Dildo de Ventosa Realista XL",
            precio: 45,
            imagen: "imagen/dildo3.jpg",
            categorias: ["dildos"],
            disponible: true,
            largo: "26 cm",
            diámetro: "4.5 cm",
            material: "Silicona Médica",
            color: "Piel",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Dildo de Ventosa Realista XS",
            precio: 25,
            imagen: "imagen/dildo5.jpg",
            categorias: ["dildos"],
            disponible: true,
            largo: "16 cm",
            diámetro: "3 cm",
            material: "Silicona",
            color: "Rosado, Blanco, Marrón Claro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #01",
            precio: 13,
            imagen: "imagen/L3.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #02",
            precio: 13,
            imagen: "imagen/L6.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #03",
            precio: 13,
            imagen: "imagen/L9.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Negro, Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #04",
            precio: 13,
            imagen: "imagen/L13.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, L",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #05",
            precio: 13,
            imagen: "imagen/L14.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Negro, Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #06",
            precio: 13,
            imagen: "imagen/L15.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "Unitalla",
            color: "Negro, Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #07",
            precio: 13,
            imagen: "imagen/L16.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "L",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #08",
            precio: 13,
            imagen: "imagen/L17.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "S, M, L",
            color: "Verde",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lencería Shein #09",
            precio: 13,
            imagen: "imagen/L18.jpg",
            categorias: ["lencería","ropa", "lencería de mujer"],
            disponible: true,
            talla: "L",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Plug Dilatador Anal Metálico",
            precio: 20,
            imagen: "imagen/plug.jpg",
            categorias: ["plugs", "anal"],
            disponible: true,
            largo: "7 cm",
            diámetro: "2.8 cm",
            material: "Metal",
            color: "Rojo",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Funda Extensora y Engrosadora de Pene",
            precio: 10,
            imagen: "imagen/funda.jpg",
            categorias: ["fundas", "hombre"],
            disponible: true,
            largo: "14 cm",
            diámetro: "5 cm",
            material: "Silicona",
            color: "Transparente",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Plugs Dilatadores Anales de Silicona",
            precio: 10,
            imagen: "imagen/plug2.jpg",
            categorias: ["plugs", "anal"],
            disponible: true,
            largo: "8 cm - 12 cm",
            diámetro: "1.3 cm - 3.6 cm",
            material: "Silicona",
            color: "Rosado, Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lengua Vibradora Estimuladora de Clítoris",
            precio: 35,
            imagen: "imagen/lengua.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "10.5 cm",
            diámetro: "3 cm",
            material: "Silicona",
            batería: "Carga USB",
            color: "Rosado",
            vibración: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lengua Vibradora",
            precio: 30,
            imagen: "imagen/lengua2.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "10 cm",
            diámetro: "3.3 cm",
            material: "Silicona Médica Suave",
            batería: "2 Pilas AAA (No Incluidas)",
            color: "Piel",
            vibración: "10 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Consolador Vibrador Estimulador de Punto G",
            precio: 40,
            imagen: "imagen/consola.jpg",
            categorias: ["vibradores", "consolador"],
            disponible: true,
            largo: "14 cm (Introducibles)",
            diámetro: "3 cm",
            material: "Silicona ABS",
            batería: "Carga USB",
            color: "Rosado",
            vibración: "10 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Consolador Vibrador de Conejito (360° Giratorio)",
            precio: 50,
            imagen: "imagen/consola2.jpg",
            categorias: ["vibradores", "consolador", "giratorios", "conejitos"],
            disponible: true,
            largo: "11 cm",
            diámetro: "3 cm",
            material: "Silicona Suave",
            batería: "Carga USB",
            color: "Amarillo, Morado",
            vibración: "10 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Consolador Vibrador Gelly",
            precio: 30,
            imagen: "imagen/consola3.jpg",
            categorias: ["vibradores", "consolador"],
            disponible: true,
            largo: "14 cm",
            diámetro: "3 cm",
            material: "Silicona Suave",
            batería: "2 Pilas AAA (No Incluidas)",
            color: "Malva, Morado, Azul, Rojo",
            vibración: "Estandar Ascendente",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador Masajeador Multifuncional",
            precio: 35,
            imagen: "imagen/masaje.jpg",
            categorias: ["vibradores", "masajeadores"],
            disponible: true,
            largo: "19.5 cm",
            diámetro: "4 cm",
            material: "Silicona ABS",
            batería: "Carga USB",
            color: "Morado",
            vibración: "20 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Huevo Vibrador",
            precio: 20,
            imagen: "imagen/huevo.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "5 cm",
            diámetro: "2.4 cm",
            material: "Silicona y Plástico",
            batería: "2 Pilas AA (No Incluidas)",
            color: "Rosado",
            vibración: "Ascendente",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Cuentas Anales de Silicona",
            precio: 20,
            imagen: "imagen/cuentanal.jpg",
            categorias: ["cuentas", "anal"],
            disponible: true,
            largo: "31 cm",
            diámetro: "2.5 cm",
            material: "Silicona",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Cuentas Anales Vibradoras",
            precio: 25,
            imagen: "imagen/cuentanal2.jpg",
            categorias: ["cuentas", "anal", "vibradores"],
            disponible: true,
            largo: "24 cm",
            diámetro: "2 cm",
            material: "Silicona",
            batería: "2 Pilas AAA (No Incluidas)",
            color: "Rosado",
            vibración: "Estandar",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Mini Vibrador de Micrófono",
            precio: 35,
            imagen: "imagen/minivib.jpg",
            categorias: ["vibradores", "mini"],
            disponible: true,
            largo: "21 cm",
            diámetro: "4.3 cm",
            material: "Silicona ABS",
            batería: "Carga USB",
            color: "Morado",
            vibración: "28 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador Y",
            precio: 15,
            imagen: "imagen/vibraY.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "10 cm",
            diámetro: "4.3 cm",
            material: "Silicona ABS",
            batería: "Bala Vibradora (Incluida)",
            color: "Rosado",
            vibración: "1 Frecuencia",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador de Ballena",
            precio: 40,
            imagen: "imagen/ballena.jpg",
            categorias: ["vibradores"],
            disponible: true,
            largo: "14.2 cm",
            diámetro: "3 cm",
            material: "Silicona ABS",
            batería: "Carga USB",
            color: "Rosado, Morado",
            vibración: "10 Frecuencia",
            control: "Mando a Distancia",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador Masajeador de Cabezal Intercambiable (5 en 1)",
            precio: 40,
            imagen: "imagen/vibraCab.jpg",
            categorias: ["vibradores", "masajeadores"],
            disponible: true,
            material: "Silicona ABS",
            batería: "Carga USB",
            color: "Morado",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Funda Extensora y Engrosadora de Pene #2",
            precio: 10,
            imagen: "imagen/funda2.jpg",
            categorias: ["fundas", "hombre"],
            disponible: true,
            material: "Silicona",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador Estimulador de Próstata",
            precio: 50,
            imagen: "imagen/vibraprost.jpg",
            categorias: ["vibradores", "hombre", "estimuladores"],
            disponible: true,
            largo: "15 cm",
            diámetro: "2.3 cm",
            material: "Silicona ABS",
            batería: "Carga USB",
            color: "Negro",
            vibración: "20 Frecuencia",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Conejito Vibrador Giratorio Telescópico",
            precio: 50,
            imagen: "imagen/conejitoTelesc.jpg",
            categorias: ["vibradores", "giratorios", "conejitos"],
            disponible: true,
            largo: "25 cm",
            diámetro: "3.5 cm",
            material: "Silicona Médica Suave",
            batería: "Carga USB",
            color: "Morado",
            vibración: "10 Frecuencia",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Plug Anal Cola de Conejo",
            precio: 20,
            imagen: "imagen/colaConejo.jpg",
            categorias: ["plugs", "colas", "conejo", "anal"],
            disponible: true,
            largo: "7 cm",
            ancho: "2.8 cm",
            material: "Metal y Algodón",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Doble Dildo",
            precio: 30,
            imagen: "imagen/dobleDildo.jpg",
            categorias: ["dildos", "doble"],
            disponible: true,
            largo: "29.8 cm",
            grosor: "3.4 cm a 2.2 cm",
            material: "Silicona Suave",
            color: "Rosado",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Anillo Vibrador, Retardante de Eyaculación y Estimulador de Clítoris",
            precio: 8,
            imagen: "imagen/anilloVibra.jpg",
            categorias: ["vibradores", "hombre", "anillos", "estimuladores"],
            disponible: true,
            diámetro: "Adaptable",
            material: "Silicona",
            batería: "Balita Vibradora (Incluida)",
            color: "Rosado",
            vibración: "Constante",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Masturbador Vibrador Realista Masculino",
            precio: 65,
            imagen: "imagen/masturbaHomb.jpg",
            categorias: ["vibradores", "hombre", "Masturbadores"],
            disponible: true,
            material: "Silicona Suave",
            batería: "Carga USB",
            vibración: "10 Modos",
            color: "Blanco",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Bomba al Vacío para Pene",
            precio: 30,
            imagen: "imagen/bomba.jpg",
            categorias: ["vibradores", "hombre", "Masturbadores"],
            disponible: true,
            largo: "22 cm",
            diámetro: "6.9 cm",
            material: "Silicona y Plástico",
            color: "Morado",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Pinzas para Pezón",
            precio: 10,
            imagen: "imagen/pinzas.jpg",
            categorias: ["pinzas", "pezón", "BDSM"],
            disponible: true,
            largo: "5.6 cm",
            material: "Metal",
            color: "Plateado",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Bolas Chinas Vibradoras",
            precio: 45,
            imagen: "imagen/bolachina.jpg",
            categorias: ["vibradores", "bolas chinas"],
            disponible: true,
            largo: "9 cm",
            diámetro: "3.6 cm",
            material: "Silicona Médica Suave",
            vibración: "Personalizada",
            control: "Por App",
            batería: "Carga USB",
            color: "Morado, Azul",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador de Braga #02",
            precio: 40,
            imagen: "imagen/braga2.jpg",
            categorias: ["vibradores", "bragas"],
            disponible: true,
            largo: "11 cm",
            diámetro: "3 cm",
            material: "Silicona Médica Suave",
            vibración: "Personalizada",
            control: "Por App",
            batería: "Carga USB",
            color: "Morado, Azul",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Arnés Strap-on sin Dildo",
            precio: 18,
            imagen: "imagen/arnesdildono.jpg",
            categorias: ["ropa", "accesorios"],
            disponible: true,
            largo: "Ajustable",
            diámetro: "Ajustable",
            material: "Sintético",
            color: "Rosado, Rojo, Negro, Azul",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "BIG Micrófono",
            precio: 45,
            imagen: "imagen/bigmicro.jpg",
            categorias: ["vibradores", "micrófono"],
            disponible: true,
            carga: "Por USB",
            vibración: "10 Modos",
            potencia: "Intensificada",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Kit BDSM de 10 Piezas",
            precio: 45,
            imagen: "imagen/kitBDSM.jpg",
            categorias: ["accesorios", "ropa", "BDSM", "lencería"],
            disponible: true,
            material: "Cuero Sintético",
            color: "Rojo, Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Plug Anal Cola de Zorro",
            precio: 20,
            imagen: "imagen/plugzorro.jpg",
            categorias: ["plugs", "anal", "colas", "zorro"],
            disponible: true,
            largo: "7 cm",
            diámetro: "2.8 cm",
            material: "Metal Algodón",
            color: "Rojo, Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Vibrador Vaginal",
            precio: 45,
            imagen: "imagen/vibraVag.jpg",
            categorias: ["vibradores", "vaginal"],
            disponible: true,
            largo: "10.3 cm",
            diámetro: "3.4 cm",
            material: "Silicona ABS",
            control: "Remoto",
            batería: "Carga USB Magnética",
            color: "Rojo, Rosado, Morado",
            vibración: "12 Frecuencias",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Juego de Esposas Sexuales",
            precio: 15,
            imagen: "imagen/espoSex.jpg",
            categorias: ["juegos", "esposas", "BDSM"],
            disponible: true,
            material: "Cuero Sintético y Felpa",
            color: "Negro",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Lubricante Íntimo",
            precio: 25,
            imagen: "imagen/lubri.jpg",
            categorias: ["lubricantes"],
            disponible: true,
            propiedades: "A Base de Agua",
            contenido: "6.8 oz (200 ml)",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Conejito Vibrador, Estimulador de Punto G",
            precio: 35,
            imagen: "imagen/vibraConejo.jpg",
            categorias: ["vibradores", "conejitos", "punto g", "estimuladores"],
            disponible: true,
            largo: "19.5 cm",
            diámetro: "3.3 cm",
            material: "Silicona y Plástico",
            batería: "Carga USB (Lithium)",
            vibración: "10 Frecuencias",
            color: "Negro, Morado, Rosado",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Dildos Realistas de Colores",
            precio: 35,
            imagen: "imagen/dildoColor.jpg",
            categorias: ["dildos"],
            disponible: true,
            largo: "21 cm",
            diámetro: "4 cm",
            material: "Silicona Médica",
            color: "Azul, Morado, Rojo, Amarillo",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Dildo Anal para Doble Penetración",
            precio: 30,
            imagen: "imagen/dildoDP.jpg",
            categorias: ["dildos", "anal", "dp"],
            disponible: true,
            largo: "12.5 cm",
            diámetro: "2.2 cm",
            material: "Silicona ABS",
            batería: "1 Pila AAA (No Incluida)",
            color: "Negro",
            vibración: "10 Modos",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
        {
            nombre: "Masturbador Masculino Realista #02",
            precio: 25,
            imagen: "imagen/mastuHomb.jpg",
            categorias: ["masturbadores", "hombre"],
            disponible: true,
            largo: "10 cm",
            diámetro: "5.5 cm",
            material: "Silicona Médica",
            color: "Piel",
            vibración: "No",
            fechaAgregado: "2026-03-10",
            oferta: false,
            descuento: 0,
            rebaja: 0,
            etiquetaOferta: ""
        },
    ]
};

const IMAGEN_DEFAULT = "img/default-product.jpg";
